language: python
python:
  - "2.7"
# command to install dependencies
install:
  - make deps
# command to run tests
script:
  - make test
# Docker build
#after_success:
#  -make docker_build
#language: python
#services:
#   -docker
language: python
services:
   -docker
python:
    -'2.7'
instal:
    -make deps
script:
 -make test
 -make lint
 -make docker_build
 -make docker_push
