language: python
python:
  - "2.7"
# command to install dependencies
install:
  - make deps
# command to run tests
script:
  - make test
#Docker build
after_success:
  -make docker_build
language: python
services:
  -docker
deploy:
  provider: heroku
  app: radiant-temple-81339
  api_key: ${HEROKU_API_KEY}
